//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Interface {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class KeyBinds : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyBinds defaultInstance = ((KeyBinds)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyBinds())));
        
        public static KeyBinds Key {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Up")]
        public global::Microsoft.Xna.Framework.Input.Keys MoveUp {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["MoveUp"]));
            }
            set {
                this["MoveUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public global::Microsoft.Xna.Framework.Input.Keys MoveRight {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["MoveRight"]));
            }
            set {
                this["MoveRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Down")]
        public global::Microsoft.Xna.Framework.Input.Keys MoveDown {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["MoveDown"]));
            }
            set {
                this["MoveDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::Microsoft.Xna.Framework.Input.Keys MoveLeft {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["MoveLeft"]));
            }
            set {
                this["MoveLeft"] = value;
            }
        }
    }
}
